[GOOGLE_APPLICATION_CREDENTIALS]
type = "service_account"
project_id = "avise-229621"
private_key_id = "d3cbf290d3ad1c7b6f080bc64ba058c27749ab71"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDH+YZr9lDQrv7t
GkScqMXU8THP5pPKJy5uuGymjBZlpsGtwOjlJusNzxzJ0zR2aJlr8Mi7STxRlOC7
tameco4mO/73IvTMObmWoSZnhR8+LePpPRXRUVhLNo1m3pkdQ3n6qINS+pRvVhiH
Kuri6EhY4/m8F/t+Jpr4jpXRP8c8UmQVoegfHHUOSEFEtD9i+azui/MOgWH3nf5R
y+uT2u8zBRoZjxDUVYz5nWQECkLWcSVgx98PT6HqZYCKZ+FOmzpotZqunpWCre+m
ylxPNIrlzhGd9Q/YCEUNLkmXJaIDxAbPhNkTO1W2rL5qwJlO4jimRVsALQl9UF8F
1Mei4RJbAgMBAAECggEAL8qYEAw9cyonXaX1+NSy9vmvtGaAMoNbqvVjbggzwBZy
2iIs5rr+2P2C/U7/Dj9gTzYr2uqdQkgIz4OSZn4tL8EN5aVSiM5Q5slbosjjVxpj
ihXhtXUx20PN1mRjhmVebQPB4t5lBBi44vDkUtc9lxTg1c2LerIiPj3hWzFZXbZM
3qIHLdpMCqZi/qyzPg2Wf28cK2hDWOYhBV6PvXPV5GgZsEz+LxtnZaQ2C/23JBme
toNzHBVTTsy6gQXn9yOMH9ypQtq/2VqlwYR2iDiMZpn9hpvz6JK2LoT6fI7QfTnP
9M6qygt2jgNtTh+kOKYNuEDUh0ooGyl53ZJnBd23RQKBgQDrWsMHN3bevzxn9eE0
yB94/fNa+Zt30xfJVewdYn2rBIWbdrD5UvLp0O9Sfu5EWcr1eDR1v0SNuV4TfTQE
/TCxqfn3dZ5BSjb6Pkl/s3BA8kCzIl86KbVY9/AmEfaSSoZ3VCoa0Ze/qDQ9p5/2
154HHd77Cq6d1sk1h1C3R4f2fQKBgQDZhEGYilOk9F3dU+VwVrro9TQazo0iQoJV
piDSunBC8ZKwpx9VDM4Fvd13F1ur0WzcZIgsHgeCYsxZ29OU+OzjORfrDKyRHpdJ
aus3ZHqvtiN2BpkSFz9Jt+lVc/OXFyDKa01IHOh+fN0VYFDnPW0IdiiHoDITZl1/
shyoOmKLtwKBgQCMVt+qovkf07rKZwS2O4sA07VUDzkUV2x8ot6bmwpCevzMehcH
ZN3ybKL4dzXOzhhHDTmC6N2RAPLG/kaRnwR1PF0QoTMPzZhA2flry2zpXUsVRi6w
eQRpG9c4bEeybfwGlcpRmZ86KquUBCtPvry9k6NN4M3E0rnCUIDh+SZq5QKBgQC7
ltwbefB5KmZpIpmVMLcxgYbWN5xwF3vf8c4M7s0ybrRbtUXIS6rCOORueK6Ol6aS
zADES4GeaSZjuLnYmHVz4SFHjT6mSQOgRZ1lwDoun54lg7svZu0l3n5VPBKwEzos
WC3mK0g3Deh9LvuW8dq+mWiKzxVgtb+dCTa9vtyOMQKBgHJN8zmUNDEWelwvni/s
VfO0lBF0dx7Rj8en7m3kzGCYfMy+z9zZUiIA3HDROVUVmLupjW7/oKZAIKcOxAkr
0e+duNhx4NnC+gSfYYiCZa2DUbHkptG99XqRDagoXfzREhez9HLNSQBSs8rMCH0s
v+wS6vTTfYKV/sAdT1b72pw9
-----END PRIVATE KEY-----
"""
client_email = "drive-admin@avise-229621.iam.gserviceaccount.com"
client_id = "109376115355472438621"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/drive-admin%40avise-229621.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
